### ISSUE TITLE
Allow for adjustment of lenght/number of dots

### ISSUE THREAD

**Issue by norbusan** [OpenLogicProject/bussproofs-extra#3]
The lenght ot the dots deduction is quite big, using up a lot of space vertically. It would be nice if one could adjust the height (length, number of dots) somehow.

**Comment by rzach** [comment]
fixed with a13ec8a . Deduce lines are now all styled with deduceLine, can be changed using tikzset

**Comment by norbusan** [comment]
Danke schön!
